Showtime is not present under alive_progress.styles
I tried running the demo commands to check the alive_progress but it wast throwing out error : 
ImportError: cannot import name showtime

So i just removed the styles and it was working fine. 
I have made changes to the read me.